// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: horses.proto

#include "horses.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace tdpalio {
class HorseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Horse>
      _instance;
} _Horse_default_instance_;
class HorsesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Horses>
      _instance;
} _Horses_default_instance_;
}  // namespace tdpalio
namespace protobuf_horses_2eproto {
void InitDefaultsHorseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tdpalio::_Horse_default_instance_;
    new (ptr) ::tdpalio::Horse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tdpalio::Horse::InitAsDefaultInstance();
}

void InitDefaultsHorse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHorseImpl);
}

void InitDefaultsHorsesImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_horses_2eproto::InitDefaultsHorse();
  {
    void* ptr = &::tdpalio::_Horses_default_instance_;
    new (ptr) ::tdpalio::Horses();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tdpalio::Horses::InitAsDefaultInstance();
}

void InitDefaultsHorses() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHorsesImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, indice_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, nome_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, colore_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, eta_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, capacita_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, selezione_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, coscia_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horse, infortunio_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horses, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdpalio::Horses, cavalli_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tdpalio::Horse)},
  { 14, -1, sizeof(::tdpalio::Horses)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tdpalio::_Horse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tdpalio::_Horses_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "horses.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014horses.proto\022\007tdpalio\"\232\001\n\005Horse\022\016\n\006ind"
      "ice\030\001 \001(\r\022\014\n\004nome\030\002 \001(\t\022\016\n\006colore\030\003 \001(\r\022"
      "\013\n\003eta\030\004 \001(\r\022\020\n\010capacita\030\005 \003(\r\022\r\n\005score\030"
      "\006 \003(\r\022\021\n\tselezione\030\007 \001(\r\022\016\n\006coscia\030\010 \001(\r"
      "\022\022\n\ninfortunio\030\t \001(\r\")\n\006Horses\022\037\n\007cavall"
      "i\030\001 \003(\0132\016.tdpalio.Horseb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 231);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "horses.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_horses_2eproto
namespace tdpalio {

// ===================================================================

void Horse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Horse::kIndiceFieldNumber;
const int Horse::kNomeFieldNumber;
const int Horse::kColoreFieldNumber;
const int Horse::kEtaFieldNumber;
const int Horse::kCapacitaFieldNumber;
const int Horse::kScoreFieldNumber;
const int Horse::kSelezioneFieldNumber;
const int Horse::kCosciaFieldNumber;
const int Horse::kInfortunioFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Horse::Horse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_horses_2eproto::InitDefaultsHorse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tdpalio.Horse)
}
Horse::Horse(const Horse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      capacita_(from.capacita_),
      score_(from.score_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  nome_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nome().size() > 0) {
    nome_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nome_);
  }
  ::memcpy(&indice_, &from.indice_,
    static_cast<size_t>(reinterpret_cast<char*>(&infortunio_) -
    reinterpret_cast<char*>(&indice_)) + sizeof(infortunio_));
  // @@protoc_insertion_point(copy_constructor:tdpalio.Horse)
}

void Horse::SharedCtor() {
  nome_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&indice_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&infortunio_) -
      reinterpret_cast<char*>(&indice_)) + sizeof(infortunio_));
  _cached_size_ = 0;
}

Horse::~Horse() {
  // @@protoc_insertion_point(destructor:tdpalio.Horse)
  SharedDtor();
}

void Horse::SharedDtor() {
  nome_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Horse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Horse::descriptor() {
  ::protobuf_horses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_horses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Horse& Horse::default_instance() {
  ::protobuf_horses_2eproto::InitDefaultsHorse();
  return *internal_default_instance();
}

Horse* Horse::New(::google::protobuf::Arena* arena) const {
  Horse* n = new Horse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Horse::Clear() {
// @@protoc_insertion_point(message_clear_start:tdpalio.Horse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  capacita_.Clear();
  score_.Clear();
  nome_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&indice_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&infortunio_) -
      reinterpret_cast<char*>(&indice_)) + sizeof(infortunio_));
  _internal_metadata_.Clear();
}

bool Horse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tdpalio.Horse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 indice = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &indice_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nome = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nome()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nome().data(), static_cast<int>(this->nome().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tdpalio.Horse.nome"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 colore = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &colore_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 eta = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &eta_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 capacita = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_capacita())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 42u, input, this->mutable_capacita())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 score = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_score())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 50u, input, this->mutable_score())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 selezione = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &selezione_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 coscia = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &coscia_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 infortunio = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &infortunio_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tdpalio.Horse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tdpalio.Horse)
  return false;
#undef DO_
}

void Horse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tdpalio.Horse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 indice = 1;
  if (this->indice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->indice(), output);
  }

  // string nome = 2;
  if (this->nome().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nome().data(), static_cast<int>(this->nome().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tdpalio.Horse.nome");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nome(), output);
  }

  // uint32 colore = 3;
  if (this->colore() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->colore(), output);
  }

  // uint32 eta = 4;
  if (this->eta() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->eta(), output);
  }

  // repeated uint32 capacita = 5;
  if (this->capacita_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _capacita_cached_byte_size_));
  }
  for (int i = 0, n = this->capacita_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->capacita(i), output);
  }

  // repeated uint32 score = 6;
  if (this->score_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _score_cached_byte_size_));
  }
  for (int i = 0, n = this->score_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->score(i), output);
  }

  // uint32 selezione = 7;
  if (this->selezione() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->selezione(), output);
  }

  // uint32 coscia = 8;
  if (this->coscia() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->coscia(), output);
  }

  // uint32 infortunio = 9;
  if (this->infortunio() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->infortunio(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tdpalio.Horse)
}

::google::protobuf::uint8* Horse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tdpalio.Horse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 indice = 1;
  if (this->indice() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->indice(), target);
  }

  // string nome = 2;
  if (this->nome().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nome().data(), static_cast<int>(this->nome().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tdpalio.Horse.nome");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nome(), target);
  }

  // uint32 colore = 3;
  if (this->colore() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->colore(), target);
  }

  // uint32 eta = 4;
  if (this->eta() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->eta(), target);
  }

  // repeated uint32 capacita = 5;
  if (this->capacita_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _capacita_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->capacita_, target);
  }

  // repeated uint32 score = 6;
  if (this->score_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _score_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->score_, target);
  }

  // uint32 selezione = 7;
  if (this->selezione() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->selezione(), target);
  }

  // uint32 coscia = 8;
  if (this->coscia() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->coscia(), target);
  }

  // uint32 infortunio = 9;
  if (this->infortunio() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->infortunio(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tdpalio.Horse)
  return target;
}

size_t Horse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tdpalio.Horse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated uint32 capacita = 5;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->capacita_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _capacita_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated uint32 score = 6;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->score_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _score_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string nome = 2;
  if (this->nome().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nome());
  }

  // uint32 indice = 1;
  if (this->indice() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->indice());
  }

  // uint32 colore = 3;
  if (this->colore() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->colore());
  }

  // uint32 eta = 4;
  if (this->eta() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->eta());
  }

  // uint32 selezione = 7;
  if (this->selezione() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->selezione());
  }

  // uint32 coscia = 8;
  if (this->coscia() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->coscia());
  }

  // uint32 infortunio = 9;
  if (this->infortunio() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->infortunio());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Horse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tdpalio.Horse)
  GOOGLE_DCHECK_NE(&from, this);
  const Horse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Horse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tdpalio.Horse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tdpalio.Horse)
    MergeFrom(*source);
  }
}

void Horse::MergeFrom(const Horse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tdpalio.Horse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  capacita_.MergeFrom(from.capacita_);
  score_.MergeFrom(from.score_);
  if (from.nome().size() > 0) {

    nome_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nome_);
  }
  if (from.indice() != 0) {
    set_indice(from.indice());
  }
  if (from.colore() != 0) {
    set_colore(from.colore());
  }
  if (from.eta() != 0) {
    set_eta(from.eta());
  }
  if (from.selezione() != 0) {
    set_selezione(from.selezione());
  }
  if (from.coscia() != 0) {
    set_coscia(from.coscia());
  }
  if (from.infortunio() != 0) {
    set_infortunio(from.infortunio());
  }
}

void Horse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tdpalio.Horse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Horse::CopyFrom(const Horse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tdpalio.Horse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Horse::IsInitialized() const {
  return true;
}

void Horse::Swap(Horse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Horse::InternalSwap(Horse* other) {
  using std::swap;
  capacita_.InternalSwap(&other->capacita_);
  score_.InternalSwap(&other->score_);
  nome_.Swap(&other->nome_);
  swap(indice_, other->indice_);
  swap(colore_, other->colore_);
  swap(eta_, other->eta_);
  swap(selezione_, other->selezione_);
  swap(coscia_, other->coscia_);
  swap(infortunio_, other->infortunio_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Horse::GetMetadata() const {
  protobuf_horses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_horses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Horses::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Horses::kCavalliFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Horses::Horses()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_horses_2eproto::InitDefaultsHorses();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tdpalio.Horses)
}
Horses::Horses(const Horses& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      cavalli_(from.cavalli_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tdpalio.Horses)
}

void Horses::SharedCtor() {
  _cached_size_ = 0;
}

Horses::~Horses() {
  // @@protoc_insertion_point(destructor:tdpalio.Horses)
  SharedDtor();
}

void Horses::SharedDtor() {
}

void Horses::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Horses::descriptor() {
  ::protobuf_horses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_horses_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Horses& Horses::default_instance() {
  ::protobuf_horses_2eproto::InitDefaultsHorses();
  return *internal_default_instance();
}

Horses* Horses::New(::google::protobuf::Arena* arena) const {
  Horses* n = new Horses;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Horses::Clear() {
// @@protoc_insertion_point(message_clear_start:tdpalio.Horses)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cavalli_.Clear();
  _internal_metadata_.Clear();
}

bool Horses::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tdpalio.Horses)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tdpalio.Horse cavalli = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_cavalli()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tdpalio.Horses)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tdpalio.Horses)
  return false;
#undef DO_
}

void Horses::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tdpalio.Horses)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tdpalio.Horse cavalli = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->cavalli_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->cavalli(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tdpalio.Horses)
}

::google::protobuf::uint8* Horses::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tdpalio.Horses)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tdpalio.Horse cavalli = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->cavalli_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->cavalli(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tdpalio.Horses)
  return target;
}

size_t Horses::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tdpalio.Horses)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .tdpalio.Horse cavalli = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->cavalli_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->cavalli(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Horses::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tdpalio.Horses)
  GOOGLE_DCHECK_NE(&from, this);
  const Horses* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Horses>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tdpalio.Horses)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tdpalio.Horses)
    MergeFrom(*source);
  }
}

void Horses::MergeFrom(const Horses& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tdpalio.Horses)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cavalli_.MergeFrom(from.cavalli_);
}

void Horses::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tdpalio.Horses)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Horses::CopyFrom(const Horses& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tdpalio.Horses)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Horses::IsInitialized() const {
  return true;
}

void Horses::Swap(Horses* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Horses::InternalSwap(Horses* other) {
  using std::swap;
  cavalli_.InternalSwap(&other->cavalli_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Horses::GetMetadata() const {
  protobuf_horses_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_horses_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tdpalio

// @@protoc_insertion_point(global_scope)
